version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/user_repository
      - SPRING_DATASOURCE_USERNAME=$postgres
      - SPRING_DATASOURCE_PASSWORD=$root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_repository
    ports:
      - "5432:5432"