spring:
  application:
    name: PonteFelveteli

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/user_repository
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

