spring:
  application:
    name: PonteFelveteli

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/user_repository
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  file:
    name: ponteFelveteliLogs.log
    path: \backend\src\main\resources\log
  level:
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

security:
  jwt:
    expiration: 31536000000
    refresh: 2592000000
  aes:
    secret: webShopProject